### ISSUE TITLE
Suggestion: Bukkit Plugin Port

### ISSUE THREAD

**Issue by samozoid** [arthomnix/spaghettitrees#5]
If the mod generates trees on fabric why should it not generate on bukkit? A way of running spaghettitrees on bukkit would be a nice convience, for example using this mod aswel with the Terra world generation.

Alternative suggestion: use a different type of server fork? such as spigot, paper, purpur, etc.

**Comment by arthomnix** [comment]
I've never developed for or used Bukkit, so I wouldn't really be able to do a port. Terra is available for Fabric if you want to try that out though
